---
layout: cv
title: Emma Ricks's Resume
---
# Emma Ricks


<div id="webaddress">
<a href="Emmalee.ricks134@gmail.com">Emmalee.ricks134@gmail.com</a>
| <a href="http://www.linkedin.com/in/emma-ricks-0174b2311/">My Linkedin page</a>
</div>

## Education

### Bachelor's in Statistics | Emphasis: Statistical Science | Minor: Natural Reosurces

**Sept. 2023 - Dec. 2027**
**Rexburg, ID, U.S.A**

*Brigham Young University--Idaho*

* Completed Applied linear regression

* Exceeded in Experimental Design

* Used statistical simulation to evaluate model assumptions

* Conducted hypothesis testing and confidence intervals with large datasets

* Interpreted statistical output to support evidence-based decisions

* Worked with biological data involving population and environmental metrics

* Completed projects involving model diagnostics and residual analysis

## Plane Crashes Project

**July 2025**
**Rexburg, ID, U.S.A**

*Brigham Young University--Idaho*

* Built a multiple logistic regression model

* Identified key factors associated with plane crash likelihood

* Used AI tools to assist in data acquisition and exploratory research

* Cleaned, organized, and analyzed aviation safety

* Developed interpretable model outputs including odds ratios and probabilities

* Effective communication and statistical reasoning

## Experience

### Teacher Aide

**Jan. 2025 - Present**
**Rexburg, ID, U.S.A**

*Math Department--Brigham Young University--Idaho*

* Led class sessions and delivered instructional material when the professor was unavailable

* Graded assignments, projects, and research papers with consistent and detailed feedback

* Supported instruction for courses in biostatistics, business statistics, and intermediate statistics

* Provided academic support that improved student comprehension and course performance

### Mathematics Tutor

**Apr. 2025 - Present**
**Rexburg, ID, U.S.A**

*Math Department--Brigham Young University--Idaho*

* Tutored 15-20 students weekly, improving their understanding of algebra and statistics

* Tracked student progress using performance metrics and helped them reach their goals

* Mentored and supported students struggling with qualitative subjects, resulting in increased test scores and confidence in math

### Skills

* R studio coding

* SQL coding

* Python coding

* Excel



<!-- ### Footer

Last updated: May 2013 -->